#!/bin/sh

# install nodejs via package manager
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs

# install build tools
sudo apt-get install -y build-essential

# install node packages
npm install

